import SwiftUI

/// Displays the chair's summary of the discussion.
struct SummaryView: View {
    let summary: String
    @State private var isExpanded = true

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                // Header
                HStack(spacing: 12) {
                    Image(systemName: "doc.text.fill")
                        .font(.title2)
                        .foregroundStyle(.blue)

                    VStack(alignment: .leading) {
                        Text("Discussion Summary")
                            .font(.title3)
                            .fontWeight(.bold)
                            .foregroundStyle(.white)

                        Text("Generated by The Chair")
                            .font(.caption)
                            .foregroundStyle(Color(hex: "#d4a843"))
                    }
                }
                .padding(.bottom, 8)

                // Summary content
                DisclosureGroup(isExpanded: $isExpanded) {
                    Text(summary)
                        .font(.body)
                        .foregroundStyle(.white.opacity(0.9))
                        .lineSpacing(6)
                        .textSelection(.enabled)
                        .padding(.top, 8)
                } label: {
                    Text("Key Findings")
                        .font(.headline)
                        .foregroundStyle(.white)
                }
                .tint(.blue)
            }
            .padding(20)
        }
        .background(Color.black)
        .navigationTitle("Summary")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(.ultraThinMaterial, for: .navigationBar)
        .toolbarColorScheme(.dark, for: .navigationBar)
    }
}

#Preview {
    NavigationStack {
        SummaryView(summary: "This is a test summary of the discussion. The participants discussed various topics and came to several conclusions.")
    }
}
